#!/bin/bash  
# Automated File Population for Holberton School Projects                       
# By Tim Britton, last edited 11/Oct/2016                                       
# Use explained in README.md in folder                                          

c=$1
d=$2
CWD=${PWD##*/}
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ "$c" != '' ] && [ "$d" != '' ]; then
    FILE=`curl -b $d https://intranet.hbtn.io/projects/$c > source`
    HEAD=`cat source | head -2 | tail -1`
    if [ "$HEAD" != '*<!DOCTYPE html>*' ]; then
	cat source | awk /"<li>File: <code>"/ | awk '{print $2}'| cut -d '>' -f2 | cut -d '<' -f1 |
	    awk '{
system("touch "$1"; echo "$1" >> README.md ")
if ($1 ~ /.c/)
system("cat template >> "$1" ")
}'
	pdir=`cat source | grep Directory | cut -d '>' -f 3 | cut -d '<' -f1 | head -1`
	if [ "$pdir" != "$CWD" ]; then
	    echo "Warning! Directory name not matching script!"
	    echo $pdir
	   fi
    else
        echo "Problem downloading page, check credentials and project #."
        exit
    fi
else
    if [ "$c" == '' ]; then
        echo "First argument needs to be project number."
    fi
    if [ "$d" == '' ]; then
        echo "Second argument needs to be cookie file."
    fi
fi
