#!/bin/bash
# Automated File Population for Holberton School Projects
# By Tim Britton, last edited 11/Oct/2016
# Use explained in README.md in folder

    HEAD=`cat source | head -2 | tail -1`
	cat source | awk /"<li>File: <code>"/ | awk '{print $2}'| cut -d '>' -f2 | cut -d '<' -f1 |
	    awk '{
system("touch "$1"; echo "$1" >> README.md ")
if ($1 ~ /.c/)
system("cat template >> "$1" ")
}'
